### ISSUE TITLE
Review or improve the error messages

### ISSUE THREAD

**Issue by cezarlz** [cezarlz/boss-validator#1]
We need to find a better way to explain to the users what is happening, why it is getting that error, etc. 

I think the current messages are "ugly". Today, we have 26 validators, so we need 26 "beautiful" messages hehe.

Can you help us? Please, enjoy! ;)

**Comment by mbad0la** [comment]
@cezarlz so we are looking to replace the existing messages with something fun and informal right? :stuck_out_tongue:

**Comment by aditya-konarde** [comment]
I would like to work on this @cezarlz. Where should I start? :)

**Comment by cezarlz** [comment]
@mbad0la and @aditya-konarde, we need to review the messages and looking for something more informal, but not something "fun". Serious, but not too much hahaha.

My english is not 100%, that's why I need your help guys :D

I think we can start reviewing the messages or replacing for something better.

Fork this project and send pull requests to master.

Thanks!

**Comment by mbad0la** [comment]
@cezarlz I'll get started asap :)

**Comment by mbad0la** [comment]
I'll also add better formatting for rules like `between`. Following example will make it clearer.
![errorimprove](https://cloud.githubusercontent.com/assets/8503331/18979818/fcac69c4-86eb-11e6-9131-156a8fe204ee.png)
This is quite unclear here what ranges our input should belong to. It seems as if only these discrete values are acceptable.

Comments @cezarlz ?

**Comment by cezarlz** [comment]
I'm agree, go ahead!

Please, see #7

**Comment by mbad0la** [comment]
@cezarlz would it make sense to have different _flavours_ of error messages? 

For eg. #7 can take care of a formalish error representation and maybe we can have a Boss method to switch to an informalish or funny representation?

What do you think? 
In my opinion, this doesn't add much functionality but it does add a bit of pre-built personalization into the module.

**Comment by cezarlz** [comment]
@mbad0la I don't, how much this will increment in lib size? The lib must also be light. I think if the user wants to do this, it can write its own messages using the existent method `configureMessages`, right?

I think we can create a separated file with alternate messages to user choose and build its own builded lib as we talk on #4 , but not increment lib size.

**Comment by mbad0la** [comment]
@cezarlz this won't increase the lib size much, as you can think of this "extension" as a data addition to your project, just like the translations we hope to have.

But I do agree with you. For the time being we should prioritise over #1 and #4. `configureMessages` is well equipped for any special use case.

**Comment by cezarlz** [comment]
I will close this issue, because I think it was resolved in #7

**Comment by mbad0la** [comment]
@cezarlz I have to implement a formatting function for options like `between`.

We'll be good to go after merging that I suppose.

**Comment by cezarlz** [comment]
@mbad0la No problem, I'm waiting for that ;)

Go ahead! 😄

**Comment by cezarlz** [comment]
Closing this issue.
