### ISSUE TITLE
[VOTE] Create a logo for boss-validator

### ISSUE THREAD

**Issue by cezarlz** [cezarlz/boss-validator#2]
Yes! I want to help many developers with this lib, that's why I love the open source community.

I chose the name `boss`, because I want to show to the user that "they will shall not pass, I'm the boss here!". A strong and fun name hehe.

I just created a simple one. What do you think? We can use the reaction system of github to vote and choose one.

![logo](https://cloud.githubusercontent.com/assets/954889/18938892/716990c2-85d2-11e6-840d-e9cdec98f970.png)

**Comment by ananay** [comment]
@cezarlz Great job on the logo!

Here's another logo I created. If you want this, I can make a PR for it. Please tell me in which directory do I have to place this?

![image](https://cloud.githubusercontent.com/assets/5569219/18940342/f1d94098-8624-11e6-8460-932543a6ce3b.png)

**Comment by ananay** [comment]
@cezarlz Great Job on the logo!

Here's another logo I created for Boss Validator. If you want this, I can create a PR for it. Please tell me in which directory do I have to place this?

![image](https://cloud.githubusercontent.com/assets/5569219/18940425/b7c28b48-8625-11e6-8701-54a6b934de4d.png)

**Comment by cezarlz** [comment]
Hi @ananay, it is a great logo! Thank you!

What do you think wait for another proposals and the votes? :D

I'm thinking of adding the logo in README.md and the future site.

Thanks!

**Comment by ananay** [comment]
Hi @cezarlz,

Sure, let's wait for more proposals. Incase you would like to use my logo, just accept this PR. :)
I've also changed the title in the README.md from "boss-validator" to "Boss Validator" to make it look more formal.

https://github.com/cezarlz/boss-validator/pull/5

**Comment by cezarlz** [comment]
Thanks @ananay 

Let us wait other proposals yet!

**Comment by kaustubhhiware** [comment]
Hi @cezarlz ,I have added a logo which suits my interpretation of the term boss-validator. 
Please consider this as a proposal.
Would like to hear your opinions about this !

**Comment by cezarlz** [comment]
Thanks @kaustubhhiware we are wating for more proposals ;)

**Comment by anthonysousa** [comment]
This is the type only option: #23

![logo](https://cloud.githubusercontent.com/assets/692423/19863294/d72929a6-9f7a-11e6-9865-10be4cded059.png)

**Comment by anthonysousa** [comment]
The last one is more fun, it's the bald angry boss option 👴 
Vertical option:
![logo-vertical](https://cloud.githubusercontent.com/assets/692423/19863465/760e4d6c-9f7b-11e6-9703-b816e5a0e352.png)

Horizontal option:
![logo-horizontal](https://cloud.githubusercontent.com/assets/692423/19863467/780d5d2e-9f7b-11e6-9c10-3bc65e71912e.png)

That's it, sorry for all the flood.

**Comment by cezarlz** [comment]
@anthonysousa I really liked all of them! I think we can work up on third options, may adjust the letter spacing between letters. What do you think?

Thanks!

**Comment by anthonysousa** [comment]
@cezarlz Great! I'm glad you liked them 😄 
I made some changes and updated the last comment. Are they better now? What do you think?
As soon as we are done with the changes, I'll update the PR files.

**Comment by cezarlz** [comment]
@anthonysousa I think it's better. I'm waiting for more proposals, on next week I will choose one.

Thanks! :D

**Comment by cezarlz** [comment]
@anthonysousa Can you create the "ui kit" and source files of logo that you create? For example, horizontal and vertical positions, only the "boss" icon without letters, etc.

Thanks!

**Comment by anthonysousa** [comment]
Great @cezarlz!
The svg files in the PR are source files, you can edit them using a SVG editor (Illustrator or Inkscape). Do you need them in another format?
By the ui kit you mean [something like this](https://d13yacurqjgara.cloudfront.net/users/13307/screenshots/864910/attachments/92273/Real_Pixels.jpg) or just some directives about colors to use, typography etc?
I'll generate the icon without the letters too.
