### ISSUE TITLE
Create structure for more language and translate the messages for each languages

### ISSUE THREAD

**Issue by cezarlz** [cezarlz/boss-validator#4]
My goal with this lib is help so many developers around the world, and our world, well, has so many languages.

Today, the `boss-validator` only supports the english language.

To start, I think these languages are more used:

* Spanish
* Portuguese (pt and pt-br)
* German
* Japanese
* Italian
* French
* Russian
* Chinese

I don't know what and how we can create the structure to support this, but I really like the approach of how this lib has used: http://numeraljs.com/

What do you think? 😄 

Please, enjoy it! 😃

**Comment by mbad0la** [comment]
Hi! 

Have a look at [this](http://airbnb.io/polyglot.js/) library by Airbnb. I think it would work for our use case. What say?

**Comment by cezarlz** [comment]
Hi @mbad0la, how are you?

I created [a lib](https://github.com/cezarlz/tribusjs) like Airbnb, but I think tribusjs it is more simple and small. But, the question is: How can we create a structure to build a extensible and easy way to extend and maintain the messages, you know?

I think we need to load not all languages first time, but the developer needs to feel free to choose your own language or all language.

Did you see the approach of Numeral.js? I thought something like that.

```javascript
// file boss-validator/languages/pt-br.js
export default {
  default: 'Por favor, preencha este campo.',
  required: 'Este campo é obrigatório',
  email: 'Insira um endereço de email válido',
  // .....
};

// main.js
let portugueseBrazil = require('boss-validator/languages/pt-br');

Boss.language(portugueseBrazil); // Call this method at any time

// or...

Boss.configureMessages(portugueseBrazil); // This method already exists and we can extend it
```

What do you think?

**Comment by mbad0la** [comment]
Hey @cezarlz , I'm fine :smile: 
Hope you are doing well too...

So, yeah. I'm pretty much okay with what you have in mind. I just have a few minor suggestions. Firstly, I would suggest using  a `Boss` instance rather than directly using it. That way, for example, we can have some locale specific defaults set.

```js
// file boss-validator/languages/pt-br.js
export default {
  default: 'Por favor, preencha este campo.',
  required: 'Este campo é obrigatório',
  email: 'Insira um endereço de email válido',
  // .....
};

// main.js

let bossInstance = new Boss(); // Sets language as the browser's language or falls back to default `en-us`

bossInstance.speak('pt-br'); // Call this method at any time

// or...

bossInstance.configureMessages('pt-br', object); // This method already exists and we can extend it using shallow merge.
```

Do you think this is better?

**Comment by cezarlz** [comment]
Hi @mbad0la,

I don't know if create the instances is a good way... I think boss-validator is a "helper", like jQuery, where we don't need create instances, you can use in everywhere. Because this lib just returns data, it don't need to storage data or the form, it just returns if form/object is valid or no. The `Boss.configureMessages` is "live".

Do you have other idea or, what do you think about I said? Or, why create instance?

**Comment by mbad0la** [comment]
Oh wait..yeah, we can do this without an _instance_. My bad...
I wanted to create an _instance_ so that I could store a default language, but that can be done without using an _instance_ as well, so I guess we can do without it.
By the way, you changed the title to `translate the messages for each language`. Does this mean I'll be using the English responses and translate them? Or will we be having seperate files for responses in different languages, as put up by you in earlier codesnippets.
Let me know your final views, I'd love to take this up and probably hack around and then we can decide what works well.

**Comment by cezarlz** [comment]
@mbad0la 

Thanks to agree. Yes, the title of this issue is confuse. I will change to `Create structure for more language and translate the messages for each languages`.

I think we can reuse the method `Boss.configureMessages` to create something better. 

I will try create today or next days. Thanks!

**Comment by cezarlz** [comment]
The new translated messages will be based on #1 

Thanks.

**Comment by mbad0la** [comment]
Yeah.... everything will fall into place then 👍

**Comment by lokhi** [comment]
Hi, I can help you for french trasnlation if you want

**Comment by cezarlz** [comment]
Hi @lokhi, yes, of course we would like your help! Please, follow the #7 for stay updated. Finishing the english translation you can translate to french based on this translation.

Thanks you so much!

**Comment by allexandresampaio** [comment]
Hi, may I help you with pt_BR translation? (Based in the english translation...)
To do so, what do I have to do?

**Comment by cezarlz** [comment]
Olá @allexandresampaio, tudo certo? Ainda está sendo criada uma estrutura para suportar outros idiomas de um jeito bem simples. Vou tentar fazer ainda essa semana, quando pronta, só fazer um fork e mandar PR ;)

--

Hi @allexandresampaio, how are you? A structure to support other languages in a very simple way is still being created. I will try to do even this week, when ready, just make a fork and send a PR;)

**Comment by allexandresampaio** [comment]
@cezarlz opa, beleza! Assim que estiver OK, me avise! 😃

**Comment by cezarlz** [comment]
Hi guys, please, see #17

**Comment by cezarlz** [comment]
@allexandresampaio está pronto! só pegar o arquivo na pasta `src/languages/pt-BR.js` ;)

@lokhi Hi, how are you? The language support is ready 🎉 , if you can help with french translation, please, just edit the file in `src/languages/fr.js`

Have a good week guys! ;)
