### ISSUE TITLE
Filters system

### ISSUE THREAD

**Issue by cezarlz** [cezarlz/boss-validator#6]
Hi guys, in the future, my idea is that boss-validator has support to filter the form or object passed as parameter.

For example:
```javascript
var form = document.querySelector('#contact');

var rules = {
  fullname: {
    required: true,
    minlength: 2,
    maxlength: 60
  },
  email: {
    required: true,
    email: true
  },
  age: {
    bigger_equal: 18,
    number: true
  },
  message: {
    required: true,
    minlength: 5,
    maxlength: 2000
  }
};

// filters are applied in index order (left -> right)
var filters = {
  fullname: ['trim', 'uppercase'],
  email: ['trim', 'lowercase', 'sanitize_email'],
  age: ['sha1'],
  message: ['base64_encode']
};

// Create a single method just to apply the filters, something like that
let filteredForm = Boss.filter(form, filters);

form.addEventListener('submit', function (e) {
  e.preventDefault();

  Boss
    .validate(form, rules, filters)
    .then((filteredData) => {
      console.log('Form is valid and filtered!', filteredData);
    })
    .catch(errors => {
      console.log('Oops..! Form is invalid, please review it.');
    });
});
```

**Comment by mbad0la** [comment]
@cezarlz what purpose do these "filters" serve?

Also, do want to take the form input and run some clean up and modifications on them right? I think using the term `normalize` would be better as filter means to choose something which satifies the conditions and if I understand correctly, you aren't choosing some of the form data from filter parameters, rather you are running some transformations on them. Am I correct?

**Comment by cezarlz** [comment]
@mbad0la yes, you are. For example, If I have an input called `name` and I put `Cezar Luiz`, I used the `filter` or `normalize` to "change" this value to `CEZAR LUIZ` using some method like `uppercase`.

I put some values and it returns a new modified value.

`normalize` sounds good.

**Comment by mbad0la** [comment]
@cezarlz I have a doubt.
Suppose, we include a transformation of _uppercase_ on a text field, then why don't we just validate that field against uppercase letters? Wouldn't it handle the condition of it having uppercase letters, altogether making the need of a transformation function redundant?

**Comment by cezarlz** [comment]
Filters != Validation. See the filters like something pos-validation, I can filter the data to send to my endpoint, for example, I have a file field and I need to upload an image, if the validation is ok, I can "transform" my image data into base64 to send to my API, endpoint, etc. Look my example above and see that my promise `then` is returning a filtered data or I can just filter my data, filter and validation can be independent methods and work together nicely. 

Got it? :)

**Comment by mbad0la** [comment]
@cezarlz yeah. Seems fair enough :+1:

**Comment by cezarlz** [comment]
I'm creating the structure for this. The branch name will be `feature/filters`. Thanks! @mbad0la

**Comment by mbad0la** [comment]
Cool!  :)

**Comment by cezarlz** [comment]
Please, I opened the PR #15 

Can you review and suggest some improvements?

Thanks!

**Comment by mbad0la** [comment]
Sure @cezarlz . I'll review it in a bit.
